package com.orbit.app.ui

enum class Language(val code: String, val displayName: String) {
    KOREAN("ko", "한국어"),
    ENGLISH("en", "English"),
    JAPANESE("ja", "日本語"),
    RUSSIAN("ru", "Русский")
}

object Localization {
    private val strings = mapOf(
        Language.KOREAN to mapOf(
            "app_subtitle" to "공간형 오프라인 코어",
            "tab_schedules" to "일정 관리",
            "tab_navigation" to "지도 및 나침반",
            "tab_sync" to "P2P 동기화 엔진",
            "tab_socket" to "AI 소켓 제어",
            "device_node_id" to "디바이스 노드 ID",
            "ai_socket_active" to "AI 소켓 활성화됨",
            "ai_socket_inactive" to "AI 소켓 비활성화됨",
            "schedules_title" to "일정 및 이벤트",
            "schedules_desc" to "오프라인 작업을 관리하고 일정 주기를 확인합니다.",
            "new_schedule" to "새 일정",
            "no_schedules" to "기록된 일정이 없습니다.",
            "reverse_lookup_title" to "일정 역연산 (기간별 누적 집계)",
            "reverse_lookup_desc" to "기준 타임스탬프를 입력하여 일/월/분기/반기/년 단위로 총 일정 수 및 누적 소요 시간을 집계합니다.",
            "evaluate_btn" to "역산 집계하기",
            "eval_match" to "집계 완료",
            "eval_no_match" to "일정이 없습니다.",
            "eval_error" to "에러: 유효하지 않은 ISO-8601 형식입니다.",
            "set_current_coords" to "1. 현재 시뮬레이션 좌표 설정",
            "lat_label" to "내 위도",
            "lon_label" to "내 경도",
            "target_event" to "2. 목적지 일정 선택",
            "no_locations" to "일정에 등록된 좌표 정보가 없습니다.",
            "compass_title" to "오프라인 나침반 포인터",
            "compass_help" to "경로 탐색을 시작하려면 왼쪽 목록에서 대상 일정을 선택하세요.",
            "bearing" to "방위각",
            "distance" to "거리",
            "duration" to "예상 소요 시간",
            "p2p_title" to "P2P 동기화 콘솔",
            "p2p_desc" to "벡터 클락을 사용해 오프라인에서 기기간 데이터베이스 델타 로그를 동기화합니다.",
            "discovered_nodes" to "발견된 피어 노드",
            "sync_now_btn" to "지금 동기화",
            "sync_console_log" to "동기화 콘솔 로그",
            "storage_opt" to "보관 최적화 대시보드 (1GB 스케일)",
            "storage_desc" to "대용량 미디어 파일 및 지도 데이터는 SQLite 파일과 분리되어 별도 파일 시스템 블롭으로 안전하게 델타 동기화됩니다.",
            "ai_title" to "AI 소켓 연동 제어판",
            "ai_desc" to "AI 에이전트가 일정 CRUD 작업을 수행할 수 있도록 로컬 웹소켓 서버를 기동합니다.",
            "config_settings" to "환경설정 구성",
            "server_status" to "서버 상태",
            "local_port" to "로컬 바인딩 포트",
            "connection_logs" to "로컬 소켓 연결 로그",
            "language_select" to "언어 선택 (Language)",
            "basic_info" to "기본 정보",
            "event_title" to "이벤트 제목",
            "start_time" to "시작 타임스탬프 (ISO-8601)",
            "end_time" to "종료 타임스탬프 (ISO-8601)",
            "geo_location" to "지리적 위치 좌표",
            "loc_name" to "위치 명칭",
            "latitude" to "위도",
            "longitude" to "경도",
            "add_recur" to "반복 규칙 설정 추가",
            "frequency" to "반복 주기",
            "interval" to "반복 간격",
            "count_limit" to "최대 횟수 제한 (선택)",
            "participants" to "참여 인원 관리",
            "display_name" to "표시 이름",
            "phone_num" to "전화번호 (필수)",
            "email_addr" to "이메일 주소 (선택)",
            "add_participant" to "참여자 추가",
            "confirm" to "확인",
            "cancel" to "취소",
            "database_sqlite" to "로컬 DB (SQLite)",
            "maps_cache" to "오프라인 지도 캐시",
            "decoupled_assets" to "분리 첨부파일",
            "tab_settings" to "설정 및 지도",
            "map_manager_title" to "오프라인 지도 매니저",
            "map_manager_desc" to "Geofabrik에서 각 국가별 지도 데이터를 다운로드하고 로드합니다. 지도를 선택하면 세계지도에 영역이 표시되며, 지도를 클릭하면 리스트의 해당 국가로 연동됩니다.",
            "active_map_label" to "활성화된 오프라인 지도",
            "download_btn" to "지도 다운로드",
            "downloading_btn" to "다운로드 중...",
            "download_complete_btn" to "설치 완료 (활성화됨)",
            "download_error" to "네트워크 오류 - 오프라인 가상 모드로 전환",
            "download_progress" to "진행률",
            "download_speed" to "다운로드 속도",
            "download_rem" to "남은 시간",
            "continent_asia" to "아시아",
            "continent_europe" to "유럽",
            "continent_north_america" to "북아메리카",
            "continent_south_america" to "남아메리카",
            "continent_africa" to "아프리카",
            "continent_australia" to "오세아니아/호주",
            "theme_mode" to "테마 모드 설정",
            "theme_dark" to "다크 모드",
            "theme_light" to "라이트 모드 (주간)"
        ),
        Language.ENGLISH to mapOf(
            "app_subtitle" to "Spatial Offline Core",
            "tab_schedules" to "Schedules",
            "tab_navigation" to "Map & Compass",
            "tab_sync" to "P2P Sync Engine",
            "tab_socket" to "AI Socket",
            "device_node_id" to "DEVICE NODE ID",
            "ai_socket_active" to "AI Socket Active",
            "ai_socket_inactive" to "AI Socket Off",
            "schedules_title" to "Schedules & Events",
            "schedules_desc" to "Manage offline tasks and evaluate schedule occurrences.",
            "new_schedule" to "New Schedule",
            "no_schedules" to "No schedules recorded yet.",
            "reverse_lookup_title" to "Schedule Aggregator (Period Totals)",
            "reverse_lookup_desc" to "Enter a reference ISO-8601 timestamp to calculate the total event count and duration by Day, Month, Quarter, Semi-annually, and Year.",
            "evaluate_btn" to "Calculate Totals",
            "eval_match" to "Calculation Complete",
            "eval_no_match" to "No schedules found.",
            "eval_error" to "Error: Invalid ISO-8601 timestamp format.",
            "set_current_coords" to "1. Set Current Simulated Coords",
            "lat_label" to "My Latitude",
            "lon_label" to "My Longitude",
            "target_event" to "2. Target Destination Event",
            "no_locations" to "No schedules have location coordinates configured.",
            "compass_title" to "Offline Destination Bearing Pointer",
            "compass_help" to "Select a destination event from the left list to enable navigation HUD.",
            "bearing" to "BEARING",
            "distance" to "DISTANCE",
            "duration" to "EST. DURATION",
            "p2p_title" to "P2P Synchronization Console",
            "p2p_desc" to "Sync database delta logs offline with nearby devices using Vector Clocks.",
            "discovered_nodes" to "Discovered Nodes",
            "sync_now_btn" to "Sync Now",
            "sync_console_log" to "Sync Console Log",
            "storage_opt" to "Storage Optimization Dashboard (1GB scale)",
            "storage_desc" to "Note: Heavy media assets and offline map slices are decoupled from SQLite. They are stored as separate filesystem blobs and delta synced directly to preserve database integrity and processing performance.",
            "ai_title" to "AI Socket Integration Controller",
            "ai_desc" to "Binds a local loopback WebSocket server for AI agent command execution and schedule CRUD operations.",
            "config_settings" to "Configuration Settings",
            "server_status" to "Server Status",
            "local_port" to "Local Binding Port",
            "connection_logs" to "Local Socket Connection Logs",
            "language_select" to "Select Language",
            "basic_info" to "Basic Information",
            "event_title" to "Event Title",
            "start_time" to "Start Timestamp (ISO-8601)",
            "end_time" to "End Timestamp (ISO-8601)",
            "geo_location" to "Geospatial Location",
            "loc_name" to "Location Name",
            "latitude" to "Latitude",
            "longitude" to "Longitude",
            "add_recur" to "Add Recurrence Rule",
            "frequency" to "Frequency",
            "interval" to "Interval",
            "count_limit" to "Count limit (optional)",
            "participants" to "Participants",
            "display_name" to "DisplayName",
            "phone_num" to "Phone (Mandatory)",
            "email_addr" to "Email (Optional)",
            "add_participant" to "Add Participant",
            "confirm" to "Confirm",
            "cancel" to "Cancel",
            "database_sqlite" to "Database (SQLite)",
            "maps_cache" to "Offline Maps Cache",
            "decoupled_assets" to "Decoupled Attachments",
            "tab_settings" to "Settings & Maps",
            "map_manager_title" to "Offline Map Manager",
            "map_manager_desc" to "Download and load offline country maps from Geofabrik. Selecting an item highlights it on the world map; clicking the map selects the corresponding region.",
            "active_map_label" to "Active Offline Map",
            "download_btn" to "Download Map",
            "downloading_btn" to "Downloading...",
            "download_complete_btn" to "Installed & Active",
            "download_error" to "Network Error - Falling back to offline simulator",
            "download_progress" to "Progress",
            "download_speed" to "Speed",
            "download_rem" to "Time Remaining",
            "continent_asia" to "Asia",
            "continent_europe" to "Europe",
            "continent_north_america" to "North America",
            "continent_south_america" to "South America",
            "continent_africa" to "Africa",
            "continent_australia" to "Australia & Oceania",
            "theme_mode" to "Theme Mode Settings",
            "theme_dark" to "Dark Mode",
            "theme_light" to "Light Mode"
        ),
        Language.JAPANESE to mapOf(
            "app_subtitle" to "空間型オフ라인コア",
            "tab_schedules" to "スケジュール",
            "tab_navigation" to "地図とコンパス",
            "tab_sync" to "P2P同期エンジン",
            "tab_socket" to "AIソケット制御",
            "device_node_id" to "デバイスノードID",
            "ai_socket_active" to "AIソケット有効",
            "ai_socket_inactive" to "AIソケット無効",
            "schedules_title" to "スケジュールとイベント",
            "schedules_desc" to "オフラインタスクを管理し、スケジュールの発生を評価します。",
            "new_schedule" to "新規スケジュール",
            "no_schedules" to "記録されたスケジュールはありません。",
            "reverse_lookup_title" to "スケジュール逆演算 (期間別累積集計)",
            "reverse_lookup_desc" to "基準のISO-8601タイムスタンプを入力し、日/月/四半期/半期/年単位でイベント数と合計所要時間を逆算集計します。",
            "evaluate_btn" to "逆算集計する",
            "eval_match" to "集計完了",
            "eval_no_match" to "スケジュールはありません。",
            "eval_error" to "エラー：無効なISO-8601形式です。",
            "set_current_coords" to "1. 現在のシミュレーション座標設定",
            "lat_label" to "マイ緯度",
            "lon_label" to "マイ経度",
            "target_event" to "2. 目的地のイベントを選択",
            "no_locations" to "スケジュールに位置座標が設定されていません。",
            "compass_title" to "オフライン目的地方位ポインタ",
            "compass_help" to "左のリストから目的地のイベントを選択してナビゲーションHUDを有効にします。",
            "bearing" to "方位角",
            "distance" to "距離",
            "duration" to "予想所要時間",
            "p2p_title" to "P2P同期コンソール",
            "p2p_desc" to "ベクトルクロックを使用して、近隣のデバイスとデータベースデルタログをオフラインで同期します。",
            "discovered_nodes" to "発見されたピアノード",
            "sync_now_btn" to "今すぐ同期",
            "sync_console_log" to "同期コンソールログ",
            "storage_opt" to "ストレージ最適化ダッシュボード（1GBスケール）",
            "storage_desc" to "注意：重いメディアアセットとオフラインマップスライスはSQLiteから分離されています。データベースの整合性と処理パフォーマンスを維持するために、直接デルタ同期されます。",
            "ai_title" to "AIソケット連携コントロールパネル",
            "ai_desc" to "AIエージェントがスケジュールCRUD操作を実行できるように、ローカルWebSocketサーバーを起動します。",
            "config_settings" to "環境設定の構成",
            "server_status" to "サーバー状態",
            "local_port" to "ローカルバインドポート",
            "connection_logs" to "ローカルソケット接続ログ",
            "language_select" to "言語の選択",
            "basic_info" to "基本情報",
            "event_title" to "イベントタイトル",
            "start_time" to "開始タイムスタンプ (ISO-8601)",
            "end_time" to "終了タイムスタンプ (ISO-8601)",
            "geo_location" to "地理的位置",
            "loc_name" to "場所名",
            "latitude" to "緯度",
            "longitude" to "経度",
            "add_recur" to "繰り返しルールの追加",
            "frequency" to "周期",
            "interval" to "繰り返し間隔",
            "count_limit" to "最大回数制限 (オプション)",
            "participants" to "参加者",
            "display_name" to "表示名",
            "phone_num" to "電話番号 (必須)",
            "email_addr" to "メールアドレス (任意)",
            "add_participant" to "参加者を追加",
            "confirm" to "確認",
            "cancel" to "キャンセル",
            "database_sqlite" to "ローカルDB (SQLite)",
            "maps_cache" to "地図キャッシュ",
            "decoupled_assets" to "個別添付ファイル",
            "tab_settings" to "設定と地図",
            "map_manager_title" to "オフライン地図マネージャー",
            "map_manager_desc" to "Geofabrikから国別の地図データをダウンロードしてロードします。選択すると世界地図に領域が表示され、地図をクリックすると該当する国が選択されます。",
            "active_map_label" to "アクティブなオフライン地図",
            "download_btn" to "地図ダウンロード",
            "downloading_btn" to "ダウンロード中...",
            "download_complete_btn" to "インストール完了（有効）",
            "download_error" to "ネットワークエラー - オフライン仮想モードに移行",
            "download_progress" to "進行状況",
            "download_speed" to "速度",
            "download_rem" to "残り時間",
            "continent_asia" to "アジア",
            "continent_europe" to "ヨーロッパ",
            "continent_north_america" to "北アメリカ",
            "continent_south_america" to "南アメリカ",
            "continent_africa" to "アフリカ",
            "continent_australia" to "オセアニア/オーストラリア",
            "theme_mode" to "テーマモード設定",
            "theme_dark" to "ダークモード",
            "theme_light" to "ライトモード"
        ),
        Language.RUSSIAN to mapOf(
            "app_subtitle" to "Пространственное автономное ядро",
            "tab_schedules" to "Расписание",
            "tab_navigation" to "Карта и Компас",
            "tab_sync" to "Синхронизация P2P",
            "tab_socket" to "AI Сокет",
            "device_node_id" to "ID УСТРОЙСТВА",
            "ai_socket_active" to "AI Сокет Активен",
            "ai_socket_inactive" to "AI Сокет Отключен",
            "schedules_title" to "Расписание и События",
            "schedules_desc" to "Управляйте автономными задачами и просматривайте повторяющиеся события.",
            "new_schedule" to "Новое Событие",
            "no_schedules" to "Расписание пока пусто.",
            "reverse_lookup_title" to "Агрегатор расписания (Итоги)",
            "reverse_lookup_desc" to "Введите эталонную метку времени ISO-8601 для расчета общего количества событий и их продолжительности по периодам.",
            "evaluate_btn" to "Рассчитать итоги",
            "eval_match" to "Расчет завершен",
            "eval_no_match" to "События не найдены.",
            "eval_error" to "Ошибка: Неверный формат времени ISO-8601.",
            "set_current_coords" to "1. Задайте текущие GPS-координаты",
            "lat_label" to "Моя Широта",
            "lon_label" to "Моя Долгота",
            "target_event" to "2. Выберите целевое событие",
            "no_locations" to "Ни у одного из событий не настроены координаты.",
            "compass_title" to "Автономный Указатель Направления",
            "compass_help" to "Выберите событие слева для запуска навигационной панели.",
            "bearing" to "НАПРАВЛЕНИЕ",
            "distance" to "РАССТОЯНИЕ",
            "duration" to "ВРЕМЯ В ПУТИ",
            "p2p_title" to "Панель P2P Синхронизации",
            "p2p_desc" to "Синхронизация локальных изменений базы данных через Векторные Часы.",
            "discovered_nodes" to "Обнаруженные Устройства",
            "sync_now_btn" to "Синхронизировать",
            "sync_console_log" to "Журнал Синхронизации",
            "storage_opt" to "Панель Оптимизации Хранилища (до 1ГБ)",
            "storage_desc" to "Примечание: Большие файлы и фрагменты карт отделены от SQLite. Они сохраняются в виде файловых блоков для стабильности СУБД.",
            "ai_title" to "Панель Управления AI-Сокетом",
            "ai_desc" to "Запуск локального WebSocket сервера для управления расписанием внешними AI-агентами.",
            "config_settings" to "Конфигурация настроек",
            "server_status" to "Статус Сервера",
            "local_port" to "Локальный Порт",
            "connection_logs" to "Локальный журнал подключений",
            "language_select" to "Выбор Языка",
            "basic_info" to "Основная Информация",
            "event_title" to "Название События",
            "start_time" to "Время Начала (ISO-8601)",
            "end_time" to "Время Окончания (ISO-8601)",
            "geo_location" to "Геопозиция",
            "loc_name" to "Название Локации",
            "latitude" to "Широта",
            "longitude" to "Долгота",
            "add_recur" to "Повторяющееся Событие",
            "frequency" to "Периодичность",
            "interval" to "Интервал",
            "count_limit" to "Лимит повторов (опционально)",
            "participants" to "Участники",
            "display_name" to "Имя пользователя",
            "phone_num" to "Телефон (Обязательно)",
            "email_addr" to "Email (Опционально)",
            "add_participant" to "Добавить Участника",
            "confirm" to "ОК",
            "cancel" to "Отмена",
            "database_sqlite" to "База данных (SQLite)",
            "maps_cache" to "Кэш оффлайн-карт",
            "decoupled_assets" to "Отдельные файлы",
            "tab_settings" to "Настройки и карты",
            "map_manager_title" to "Менеджер оффлайн-карт",
            "map_manager_desc" to "Скачивайте оффлайн-карты стран из Geofabrik. Выбор элемента подсвечивает его на карте; клик по карте выбирает соответствующий регион в списке.",
            "active_map_label" to "Активная оффлайн-карта",
            "download_btn" to "Скачать карту",
            "downloading_btn" to "Скачивание...",
            "download_complete_btn" to "Установлено и активно",
            "download_error" to "Ошибка сети - переключение в режим симуляции",
            "download_progress" to "Прогресс",
            "download_speed" to "Скорость",
            "download_rem" to "Осталось времени",
            "continent_asia" to "Азия",
            "continent_europe" to "Европа",
            "continent_north_america" to "Северная Америка",
            "continent_south_america" to "Южная Америка",
            "continent_africa" to "Африка",
            "continent_australia" to "Австралия и Океания",
            "theme_mode" to "Настройки темы",
            "theme_dark" to "Темная тема",
            "theme_light" to "Светлая тема"
        )
    )

    fun get(key: String, lang: Language): String {
        return strings[lang]?.get(key) ?: strings[Language.ENGLISH]?.get(key) ?: key
    }
}
